### ISSUE TITLE
Size property doesn't work !?

### ISSUE THREAD

**Issue by alamboley** [binouze/HTMLBitmapFonts#1]
Hey, thanks for this awesome extension!

I've some issues concerning the fontSize of my HTMLTextField:
- the fontSize property doesn't work.
- the size as an xml property doesn't work.
- all the stuff concerning the globalScale seems to be commented.

So how can I change the size of my TextField? At the moment it sounds that I'm limited to the one I generated with my Texture Atlas.
Also it seems that TextField is a little blurred.

``` actionscript3
new HTMLTextField(800, 800, 'Starling <color="#FF0000">does not cost a dime</color>. <s="10">Starling is a pure ActionScript 3</s> library', "Square721", 80, 0xFFFFFF);
```

**Comment by binouze** [comment]
Yes HTMLTextField can only use sizes that you have added to the registerBitmapFont() function. 
No scale is applied on the characters. 
I just uncomment the globalscale stuff sorry for the mistake.
In the last commit i added an autoCR variable to be able to enable or disable auto line break on the text.
I'm trying to find a way to use scaling on characters whaen the font size is not available using the nearest available size but i don't have many time to do that for the moment.

**Comment by binouze** [comment]
Hi, sorry for the late response, i was on holidays. 
I updated the library on start of december, HTMLTextField now use scaling so you can use any size you want in your texts :) 
See the github main page for other changes.
