### ISSUE TITLE
Starling 2.0

### ISSUE THREAD

**Issue by IPv6** [binouze/HTMLBitmapFonts#2]
Hello! Are there any plans to upgrade extension for starling 2.0? :)

**Comment by binouze** [comment]
Yes sure. For now I just changed all the Quad / QuadBatch with Mesh / MeshBatch for a project I work on and it work. But I wanted to see if I can do something better with the TextCompositor before to upgrade the version on Git. I'm on holidays for now ( I'm dad for the second time :D ) But I will push the v2 compatible version when I got some  time.

**Comment by IPv6** [comment]
Pretty cool, thank you for great work.
Will wait then :)

**Comment by binouze** [comment]
Ok, I just updated the extension for Starling V2 compatibility. I didn't take a look to use the ITextCompositor for now as I am very busy, but it should work ;)
